### PR TITLE
Allow reporting of Unit Tests on Jenkins CI with "RspecJunitFormatter"

### PR DESCRIPTION
**Pull request by jgebal**
Added JUnit Formatter to Gemfile for reporting Unit Tests outcomes onJenkins CI.

### CODE REVIEW

**Comment by javornikolov** [comment]
Thank you @jgebal , looks good to me. Can we just update the comment message to "imperative present tense" (as per Git guidelines https://git-scm.com/book/ch5-2.html)

**Comment by jgebal** [comment]
Thanks for the guideline.
Will this do?
"Allow reporting of Unit Tests on Jenkins CI with "Rspec JUnit Formatter"

**Comment by javornikolov** [comment]
Looks OK to me now. Thanks! Merging...

**Comment by jgebal** [comment]
Can we do same for ruby-plsql-spec?

**Comment by javornikolov** [comment]
I think yes. Also it might be useful to add a note somewhere about setting up ruby-plsql* with Jenkins or other CI servers (I guess it's a common question).

**Comment by jgebal** [comment]
Good idea.
Will do it when I catch breath.

**Pull request merged**
