### PR TITLE
Run CI with GitHub Actions to run Oracle database 18c

### PR DESCRIPTION
**Pull request by yahonda**
This draft/wip pull request runs CI with GitHub Actions. It runs Oracle Database 18c XE.
Many specs fail due to #187

### CODE REVIEW

**Comment by jgebal** [comment]
@yahonda 
You might use our Dockerfiles to build docker images and put them into DockerHub.
Our images use minimal Oracle DB (stripped of a lot of stuff). They should work fine for ruby-plsql I think.

Full instructions along with working example of travis.yml, can be found here:

https://github.com/OraOpenSource/Logger/pull/230

The Travis will take a bit more download Oracle DB and start it, but it is still reasonable time.

Hope his will help you kickstart on multi-DB builds.

How to organize your build matrix to make build time acceptable is a separate issue :)

**Comment by yahonda** [comment]
@jgebal Thanks for the useful information. I still prefer not to build Oracle database docker images by myself, I think we need to address #187 first then run CI against 18c 18.3 will be a good idea.

Also yes, building matrix will be another issue to be tackled.

**Comment by jgebal** [comment]
I'm not sure how will you install Oracle 18 XE on Travis.
Docker image seems most viable and reasonable.
The official Oracle Docker file is huge and pulling it from hub takes precious time in your build.
This is why we've created slim images that are a lot smaller and good-enough for the framework needs.

**Comment by yahonda** [comment]
Let's leave it open.

**Comment by yahonda** [comment]
Let's keep it open.

**Comment by yahonda** [comment]
Since #196 has been merged to support Oracle 18c, I think this pull request can be merged.

**Pull request closed without merging**
