### PR TITLE
Add ruby 2.4.0 support

### PR DESCRIPTION
**Pull request by javornikolov**
Ruby 2.4.0 support

### CODE REVIEW

**Comment by yahonda** [comment]
https://github.com/kubo/ruby-oci8/pull/144 is needed to use Ruby 2.4.

**Comment by javornikolov** [comment]
> kubo/ruby-oci8#144 is needed to use Ruby 2.4.

Thank you @yahonda! I added a Gemfile to the build matrix (maybe just temporarily) for ruby-oci8 master branch.

Seems we have some caveats about binding integers (`Fixnum` is passed to binding directly, `Bignum` is wrapped in `OraNumber`). Hence I suspected that binding is not supported for very large integers. Yet my attempt to break it in that way didn't succeed so I'm not quite sure whether that machinery is still needed.

**Comment by yahonda** [comment]
ruby-oci8 2.2.3 has been out including kubo/ruby-oci8#144 then we do not need https://github.com/rsim/ruby-plsql/pull/119/commits/bfa43e33a62932011a02e92b9a7fcbc7228b60c9 anymore.

**Comment by javornikolov** [comment]
> ruby-oci8 2.2.3 has been out including kubo/ruby-oci8#144 then we do not need bfa43e3 anymore.

Thank you for the notification @yahonda! I just removed the redundant commit.

I'm still trying to figure out whether special treating for `Bignum` and `Fixnum` is still necessary (kubo/ruby-oci8/pull/148)

**Comment by yahonda** [comment]
json 1.8.3 is not supported with Ruby 2.4. Adding this entry to `gemfiles/Gemfile.activerecord-4.1` and `gemfiles/Gemfile.activerecord-4.2` addressed them but it gets another error running with Ruby 1.9.3.


```ruby
    gem 'json', git: 'https://github.com/flori/json', branch: 'v1.8' if
```

Here is the [commit] (https://github.com/yahonda/ruby-plsql/commit/f4a1f170f188ce854cb976cb987579e93ef8b02e) to support json 1.8 with Ruby 2.4.0 and [errors with Ruby 1.9.3](https://travis-ci.org/yahonda/ruby-plsql/builds/187278005)

**Comment by javornikolov** [comment]
For ActiveRecord 4.2 there is an effort to deal with that in 4-2-stable branch by removing the json dependency (rails/rails#26334). For 4.1 maybe the way to go would be declaring support for ruby < 2.4 only.

**Comment by javornikolov** [comment]
@yahonda, somehow I managed to find workarounds for the issues by picking some gems from their maintenance git branches if ruby version is >= 2.4.0:
* For activerecord 4.1 using your suggestion (0755808)
``` ruby
  gem 'json', github: 'flori/json', branch: 'v1.8
```
* For activerecord 4.2 (90126ea)
``` ruby
  gem 'activerecord', github: 'rails/rails', branch: '4-2-stable'
```
* The `undefined method 'spec' for nil:NilClass` for ruby 1.9.3 was bundler problem (solved by updating bundler before the build)

**Pull request merged**
